print("Hello from lesson 8")
num1=int(input("what is da first num"))
num2=int(input("what is da first num"))
num3=int(input("what is da first num"))
num1=int(input("what is da first num"))
num1=int(input("what is da first num"))