print("Hello from lesson 8")
num1=int(input("what is da first num"))
num2=int(input("what is da second num"))
num3=int(input("what is da third num"))
num4=int(input("what is da  num"))
num5=int(input("what is da first num"))